### ISSUE TITLE
Eolementhe: issue with AIblock Videoindexer  - server files 

### ISSUE THREAD

**Issue by Videomenthe** [eolementhe/guide#9] opened 2024-02-22 12:52 UTC
When selecting ingest= server files ,  use AI block with VideoIndexer, error: code: could not upload video appears.

**Comment by Videomenthe** [comment] 2024-02-22 12:53
![MicrosoftTeams-image (2)](https://github.com/eolementhe/guide/assets/23049890/c587e3fe-75bd-4ef9-8742-5588cb962556)

**Comment by AntoineTohan** [comment] 2024-02-27 11:14
Duplicate of #7999

**Closed as completed by AntoineTohan** 2024-02-27 11:14 UTC
